CopenhagenCityArchives/collections-online

- app/styles/search-results-item.scss
> Add hover effect on search results images

- app/styles/filterbar.scss
- app/styles/list-view.scss
- app/styles/map-view.scss
> Full width map on desktop

- app/scripts-browserify/map.js
- app/scripts-browserify/markerclusterer.js
- app/scripts-browserify/search/es-aggregations-body.js
- app/scripts-browserify/search/es-query-body.js
- app/scripts-browserify/search/geohash.js
- app/scripts-browserify/search/index.js
- app/scripts-browserify/view-mode.js
- app/views/includes/map.pug
- app/views/includes/search-filter-sidebar.pug
- lib/config.js
- lib/controllers/api.js
- lib/controllers/geo-tagging.js
- lib/services/elasticsearch.js
- package-lock.json
- package.json
- Added a lot of comments
- Split the update-logic in search/index.js up into seperate parts for the map
and list-view.
- Did a number of renames to make the code more readable. Eg. freshUpdate becomes
updateWidgets as thats what the bool was used for
- Added TODOs in parts of the code that is known to not work
- We now switch how to get data for the map based on zoom-levels, zoomed out we
produce geohash results, when zoomed in we use regular asset results
- Tweaked the amount of data we get back in search-results to only include the
source-field we need for presentation
- The map now auto-updates when moved
- Geo-searches are made within bounds coorsponding to the map
- Images for markers are loaded asynchronously
> Major refactor of the map functionality and implementation of geo hashing

- app/styles/filterbar.scss
- app/views/includes/filterbar.pug
> Add "(BETA)" text to map button

- app/scripts-browserify/map.js
> Fix closing of infoboxes

- app/scripts-browserify/view-mode.js
- app/styles/filterbar.scss
- app/styles/list-view.scss
- app/views/includes/filterbar.pug
> Make list view default

- app/scripts-browserify/view-mode.js
> Fix list view

- app/styles/filterbar.scss
> Fix filter button styling

- app/styles/list-view.scss
- app/styles/map-view.scss
- app/styles/search-results.scss
> Fix list and map styling

- app/scripts-browserify/map.js
- app/scripts-browserify/search/index.js
- app/scripts-browserify/view-mode.js
> Refresh search when view-mode is changed

- app/styles/list-view.scss
> Hide filters above results in list view

- app/scripts-browserify/search/filter-sidebar.js
> Remove geobounds from filter box

- app/scripts-browserify/map.js
- app/styles/map-view.scss
> Fix thumbnail image scaling on map

- app/scripts-browserify/map.js
- app/views/includes/search-results-item.pug
- docs/FEATURES.md
> Open map/list photos in new window

- app/styles/search-freetext-form.scss
> Add jumbo search underline

- app/scripts-browserify/search/filter-sidebar.js
- app/scripts-browserify/search/index.js
- app/styles/filterbar.scss
- app/views/mixins/search-filter-section.pug
> Map filters

- app/scripts-browserify/search/index.js
> Add description to list view

- lib/config.js
> Adjust cluster zoom level

- app/styles/filterbar.scss
- app/views/includes/filterbar.pug
> Don't show sorting on map view

- app/scripts-browserify/auth.js
- lib/services/auth0.js
- plugins/auth.js
- shared/helpers.js
> Port the login/logout part of the auth0 integration to Universal Login

- app/styles/list-view.scss
- app/styles/search-results.scss
> Show count in mobile header on list view

- app/styles/filterbar.scss
- app/styles/topbar.scss
> Fix username length

- app/styles/filterbar.scss
- app/styles/mobile-filter.scss
- app/views/includes/search-filter-chosen-filters.pug
> Fix chosen filters font

- app/views/includes/motif-tagging.pug
- app/views/includes/motif-tagging/tag-suggestions.pug
- lib/config.js
> Disable vision tag suggestions

- app/views/includes/row-types/map-coordinates.pug
- lib/helpers.js
> Show compass direction if configured to

- app/views/includes/row-types/map-coordinates.pug
> Style assets on desktop

- app/views/includes/motif-tagging.pug
> Fix column width when vision tags are disabled

- app/scripts-browserify/search/index.js
- app/views/includes/map.pug
- lib/config.js
> Integrated the search controller with the latests map-controller

- app/views/includes/relations.pug
- lib/controllers/document.js
> No backside assets in related

- app/views/includes/row-types/map-coordinates.pug
> Add more blocks to map + info template

- app/styles/main.scss
- app/styles/topbar.scss
> Asset mobile styling

- app/scripts-browserify/base.js
- app/views/document.pug
> Make it possible to override the stock map-view

- app/views/includes/motif-tagging.pug
> Emneord --> Brugernes emneord

- app/views/includes/motif-tagging/tags.pug
> Nogen --> nogle

- app/views/frontpage.pug
- app/views/mixins/galleries.pug
- plugins/keystone/models/galleries.js
> Add 'block' gallery apperance

- app/views/mixins/galleries.pug
> Fix carousel gallery thumbnail size

- app/scripts-browserify/sidebar-menu.js
- app/styles/topbar.scss
- app/views/includes/sidebar-menu.pug
- plugins/keystone/menus.js
- plugins/keystone/models/menu-items.js
> Add sub menus

- lib/config.js
- lib/controllers/index.js
- plugins/keystone/models/index.js
- plugins/keystone/models/jumbo-items.js
> Implement jumbo items in KeystoneJS

- app/scripts-browserify/search/filter-sidebar.js
- app/scripts-browserify/search/generate-querystring.js
- app/scripts-browserify/search/get-parameters.js
- app/scripts-browserify/search/index.js
- app/scripts-browserify/view-mode.js
- app/views/includes/filterbar.pug
And use it to set map state on init.
This PR also makes the map being the default if a "map" url parameter exists.
KB-436
KB-354
> Add map centerpoint and zoom to url

- app/scripts-browserify/galleries.js
> Fix Slick buttons

- app/scripts-browserify/view-mode.js
- app/styles/map-view.scss
> Fix mobile map and filterbar tab active styling

- app/views/includes/filterbar.pug
> Remove beta from map tab

- app/scripts-browserify/sidebar-menu.js
- app/views/includes/sidebar-menu.pug
> Icon for mobile menu items with children

- app/styles/topbar.scss
> Fix auth dropdown

- app/styles/topbar.scss
> Fix padding in topbar menu dropdown options

- app/scripts-browserify/search/index.js
This way we don't have to rely on the map-controller to have a default.
KB-448
> Pick up initial center from configuration.

- app/styles/topbar.scss
> Fix dropdown option padding in menu

- app/scripts-browserify/search/index.js
> Handle race-condition that caused filters to break

- app/styles/map-view.scss
> Fix map update on mobile when changing filters

- app/scripts-browserify/search/index.js
As a part of this do some cleanup of how we trigger the view-mode for returning
users - make sure to strip the "map" part off of the url to allow users returning
to the list-view mode to end up in it.
KB-471
> Use the browser state when returning from a asset view.

- app/scripts-browserify/search/index.js
- app/styles/map-view.scss
> Freeze map properties while the filter-menu is visisble

- app/views/sitemaps/urlset.pug
- app/views/urlset.pug
- lib/controllers/sitemap.js
> Fix issues with the sitemap

- plugins/keystone/menus.js
- plugins/keystone/models/menu-items.js
> Refactor menus.js into a menubuilder that supports submenus

- app/styles/search-results.scss
> Fix search header text in Chrome

- app/views/includes/sidebar-menu.pug
- plugins/keystone/menus.js
> Fix mobile menu links and order

- app/styles/topbar.scss
> Fix link padding in topbar menu

- lib/services/auth0.js
- package-lock.json
- package.json
- plugins/auth.js
> Edit profile

- build/gulp.js
- package-lock.json
- package.json
> Upgrade gulp

- app/scripts-browserify/search/es-aggregations-body.js
- app/scripts-browserify/search/es-query-body.js
- app/scripts-browserify/search/index.js
> Support date period ranges

- app/scripts-browserify/search/es-aggregations-body.js
- app/scripts-browserify/search/es-query-body.js
- app/scripts-browserify/search/index.js
This PR is probably a bit easier to understand if compared with master instead of testing.
https://github.com/CopenhagenCityArchives/collections-online/compare/master...CopenhagenCityArchives:feature/KB-498-period-range-agg
KB-498
> New approach to period date filters.

- app/views/document.pug
> Add photographer and catalog to social media metadata

- package-lock.json
- package.json
> Update keystone from 4.0.0-beta1 to 4.1.0

- app/scripts-browserify/search/generate-querystring.js
- app/scripts-browserify/search/get-parameters.js
- app/scripts-browserify/search/index.js
> Improve the Historisk Atlas integration with a "secondary map" state

- lib/controllers/stream.js
- lib/routers/asset.js
- shared/helpers.js
> Add a simple stream-based controller.

- app/views/includes/feedback.pug
- app/views/includes/geo-tagging.pug
- app/views/includes/motif-tagging.pug
- app/views/mixins/date-interval-range-picker.pug
- app/views/mixins/search-freetext-form.pug
> Add aria-labels to input fields

- app/views/includes/navigator-preview.pug
- app/views/includes/search-results-item.pug
- app/views/mixins/galleries.pug
> Add missing alt texts

- app/scripts-browserify/cookie-consent.js
> Fix wcag issues by correcting a aria-describedby reference and improving a link-tekst

- app/views/mixins/meta.pug
- app/views/page.pug
- plugins/keystone/models/pages.js
> Add some fields to the keystone page type and render them
